terrorism = ['abu_sayyaf', 'afghanistan', 'agro', 'al-qaeda', 'al-qaeda_in_the_arabian_peninsula', 'al-qaeda_in_the_islamic_maghreb', 'al-shabaab', 'ammonium_nitrate', 'attack', 'biological_weapon', 'car_bomb', 'chemical_weapon', 'conventional_weapon', 'dirty_bomb', 'eco-terrorism', 'environmental_terrorism', 'euskadi_ta_askatasuna', 'extremism', 'farc', 'fundamentalism', 'hamas', 'hezbollah', 'improvised_explosive_device', 'iran', 'iraq', 'irish_republican_army', 'islamist', 'jihad', 'nationalism', 'nigeria', 'nuclear', 'nuclear_enrichment', 'pakistan', 'palestine_liberation_front', 'pirates', 'plo', 'political_radicalism', 'recruitment', 'somalia', 'suicide_attack', 'suicide_bomber', 'taliban', 'tamil_tigers', 'tehrik-i-taliban_pakistan', 'terror', 'terrorism', 'weapons-grade', 'yemen']

terrorism_short_terms = ['abu_sayyaf', 'al-qaeda', 'al-qaeda_in_the_arabian_peninsula', 'al-qaeda_in_the_islamic_maghreb', 'al-shabaab', 'ammonium_nitrate', 'biological_weapon', 'car_bomb', 'chemical_weapon', 'conventional_weapon', 'dirty_bomb', 'eco-terrorism', 'environmental_terrorism', 'euskadi_ta_askatasuna', 'extremism', 'farc', 'fundamentalism', 'hezbollah', 'improvised_explosive_device', 'irish_republican_army', 'jihad', 'nuclear_enrichment', 'palestine_liberation_front', 'political_radicalism', 'suicide_attack', 'suicide_bomber', 'taliban', 'tamil_tigers', 'tehrik-i-taliban_pakistan', 'weapons-grade']

terrorism_long_terms = ['afghanistan', 'hamas', 'iran', 'iraq', 'islamist', 'nationalism', 'nigeria', 'pakistan', 'somalia', 'terrorism', 'yemen']

terrorism_black_list = ['agro', 'attack', 'nuclear', 'pirates', 'plo', 'recruitment', 'terror']

domestic = ['air_marshal', 'alcohol_and_tobacco_tax_and_trade_bureau', 'border_patrol', 'bureau_of_land_management', 'central_intelligence_agency', 'coast_guard', 'customs_and_border_protection', 'dea', 'emergency_management', 'espionage', 'federal_air_marshal_service', 'federal_aviation_administration', 'federal_bureau_of_investigation', 'federal_emergency_management_agency', 'fusion_center', 'homeland_defense', 'national_guard', 'secret_service', 'secure_border_initiative', 'task_force_88_(anti-terrorist_unit)', 'transportation_security_administration', 'u.s._immigration_and_customs_enforcement', 'united_nations', 'united_states_citizenship_and_immigration_services', 'united_states_department_of_homeland_security']

domestic_part1 = ['air_marshal', 'alcohol_and_tobacco_tax_and_trade_bureau', 'border_patrol', 'bureau_of_land_management', 'central_intelligence_agency', 'coast_guard']
domestic_part2 = ['customs_and_border_protection', 'dea', 'emergency_management', 'espionage', 'federal_air_marshal_service', 'federal_aviation_administration']
domestic_part3 = ['federal_bureau_of_investigation', 'federal_emergency_management_agency', 'fusion_center', 'homeland_defense', 'national_guard', 'secret_service']
domestic_part4 = ['secure_border_initiative', 'task_force_88_(anti-terrorist_unit)', 'transportation_security_administration', 'u.s._immigration_and_customs_enforcement', 'united_nations', 'united_states_citizenship_and_immigration_services', 'united_states_department_of_homeland_security']